name: Build CI

on:
  workflow_dispatch:
  push:
    tags:
      - "v*.*.*"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js 14.x
        uses: actions/setup-node@v1
        with:
          node-version: 14.x

      - run: yarn --ignore-engines


      - run: yarn run build
        env:
          PRO_COMPONENTS_CI: CI

      - name: publish to npm
        run: |
          cd packages/table
          npm publish -r --access public
        env:
          NODE_AUTH_TOKEN: ${{secrets.NPM_ACCESS_TOKEN}}
